runtime: python
env: flex
entrypoint: gunicorn -b :$PORT hello_world:me

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.10"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  REACT_APP_FIREBASE_API_KEY: "your_api_key_here"
  REACT_APP_FIREBASE_AUTH_DOMAIN: "your_auth_domain_here"
  REACT_APP_FIREBASE_PROJECT_ID: "your_project_id_here"
  REACT_APP_FIREBASE_STORAGE_BUCKET: "your_storage_bucket_here"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "your_messaging_sender_id_here"
  REACT_APP_FIREBASE_APP_ID: "your_app_id_here"
  REACT_APP_FIREBASE_MEASUREMENT_ID: "your_measurement_id_here"